display:
model: epd2in13_V3 # or epd2in9, epd2in7, etc.
rotation: 0 # 0/90/180/270
refresh_seconds: 60 # full refresh cadence
invert_down: true # show red/black style with arrows


symbols:
 - type: stock
   symbol: AAPL
   label: AAPL
 - type: stock
   symbol: TSLA
   label: TSLA
 - type: crypto
   symbol: BTC-USD
   label: BTC