display:
  model: epd2in13_V4
  rotation: 0
  refresh_seconds: 60
  invert_down: true

symbols:
 - type: stock
   symbol: AAPL
   label: AAPL
 - type: stock
   symbol: TSLA
   label: TSLA
 - type: crypto
   symbol: BTC-USD
   label: BTC